# ---------------------------
# DATASOURCE CONFIGURATION
# ---------------------------
spring.datasource.url=jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres?user=postgres.nzdfurdfnrlhgqhhdogd&password=vymVk5tIftth9lOE
spring.datasource.username=postgres.nzdfurdfnrlhgqhhdogd
spring.datasource.password=vymVk5tIftth9lOE
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048

# ---------------------------
# JPA / HIBERNATE
# ---------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.use_legacy_prepared_statement_naming=true
spring.jpa.show-sql=true

# ---------------------------
# MAIL
# ---------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gonegift.team@gmail.com
spring.mail.password=fxfp aqhm dngs iwdf 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# LifeBuddy
lifebuddy.mail.username=lifebuddy.gonegift@gmail.com
lifebuddy.mail.password=mgjq lznv iuap xlys 

# ---------------------------


# ---------------------------
# SERVER
# ---------------------------
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=true

# ---------------------------
# LOGGING
# ---------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
